stages:
    - build
    - sonarqube-check

variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"

cache:
    key: "${CI_JOB_NAME}"
    paths:
        - .sonar/cache

build_project:
    stage: build
    image: alpine:latest
    before_script:
        - apk update
        - apk add --no-cache gcc make cmake doxygen graphviz musl-dev
    script:
        - mkdir -p ./build/
        - cd ./build/
        - cmake ..
        - make all
        - make docs
    artifacts:
        paths:
            - build/
            - .scannerwork/

sonarqube-check:
    stage: sonarqube-check
    image:
        name: sonarsource/sonar-scanner-cli:5.0
        entrypoint: [""]
    script:
        - sonar-scanner
    dependencies:
        - build_project
    allow_failure: true
