image: alpine:latest

stages:
    - build

before_script:
    - apk update
    - apk add --no-cache gcc make cmake musl-dev libxml2-dev

build_project:
    stage: build
    script:
        - mkdir -p ./build/
        - cd ./build/
        - cmake ..
        - make
