image: alpine:latest

stages:
    - build

before_script:
    - apk update
    - apk add --no-cache gcc make cmake rsync doxygen graphviz musl-dev openssh-client

    - eval $(ssh-agent -s)
    - chmod 600 "${SSH_PRIVATE_KEY}"
    - ssh-add "${SSH_PRIVATE_KEY}" > /dev/null

    - mkdir -p ~/.ssh/
    - chmod 700 ~/.ssh/
    - ssh-keyscan -H "${DEPLOY_HOST}" >> ~/.ssh/known_hosts

build_project:
    stage: build
    script:
        - mkdir -p ./build/
        - cd ./build/
        - cmake ..
        - make all
        - make docs

        - rsync -avz --delete ../docs/ "${DEPLOY_USER}"@"${DEPLOY_HOST}":/var/www/nyxlib.org/node/
