[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nyx-node"
version = "1.0.0b5"
description = "Python bindings for NyxNode"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
authors = [
    {name = "Jérôme ODIER", email = "jerome.odier@lpsc.in2p3.fr"},
]

[tool.hatch.build.targets.wheel]
packages = ["nyx"]
